site_name: LoTusY的学习笔记
site_author: LoTusY
theme:
  name: material
  palette:
    primary: indigo # 网站主色调

nav:
  - 首页: index.md
  - 大模型理论基础:
    - 注意力机制解析: deep-learning/attention.md
    - 线性回归解析: deep-learning/Linear_Regression.md
    - Softmax回归解析: deep-learning/Softmax_Regression.md
    - 多层感知机解析: deep-learning/MLP.md
    - 权重衰减解析: deep-learning/Weight_Decay.md
    - Dropout层解析: deep-learning/Dropout.md
    - 前向传播与反向传播解析: deep-learning\Computational_Graph.md
  - PyTorch 开发笔记:
    - Tensor 原地操作与内存优化: attention/python.md
    - 张量维度与求和: attention/Linear_Algebra.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js